// Convert the sport-skill compilations (snowboard, hockey) into skills.yaml —
// same shape as exercises.yaml, so the library treats them as extra sections.
//
// The "skills list" sheets interleave section headers with skills (many of
// which have no video link), so headers can't be detected by "no URL" alone.
// We key the known section labels per sheet; a row is a header only if it has
// no URL and matches that set — everything else is a skill under the current
// section.

import XLSX from 'xlsx';
import { writeFileSync } from 'node:fs';

const D = `${process.env.HOME}/Downloads`;
const clean = (v) => String(v ?? '').replace(/\s+/g, ' ').trim();
const slug = (s) =>
	clean(s).toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

const SOURCES = [
	{
		file: 'Skills Work.xlsx',
		sheet: 'skills list',
		category: 'snowboard-skills',
		idPrefix: 'sb',
		headers: ['..home practice..', 'basics/warmup', 'features', 'flat ground', 'jumps', 'rotation']
	},
	{
		file: 'Hockey Skills Work.xlsx',
		sheet: 'skills list',
		category: 'hockey-skills',
		idPrefix: 'hk',
		headers: ['arms & ankles', 'backward', 'edges', 'shot', 'speed', 'stick handling', 'stops', 'transitions', 'uncategorized']
	}
];

const entries = [];
const seen = new Set();
for (const src of SOURCES) {
	const wb = XLSX.readFile(`${D}/${src.file}`);
	const rows = XLSX.utils.sheet_to_json(wb.Sheets[src.sheet], { header: 1, blankrows: false, defval: '', raw: false });
	let group = '';
	for (const r of rows) {
		const name = clean(r[0]);
		const url = clean(r[1]);
		if (!name) continue;
		if (!url && src.headers.includes(name.toLowerCase())) {
			group = name.replace(/^\.+|\.+$/g, '').trim(); // "..Home Practice.." → "Home Practice"
			continue;
		}
		let id = `${src.idPrefix}-${slug(name)}`;
		let n = 2;
		while (seen.has(id)) id = `${src.idPrefix}-${slug(name)}-${n++}`;
		seen.add(id);
		entries.push({ name, id, category: src.category, group: group || undefined, url: url || undefined });
	}
}

// Emit YAML by hand to match exercises.yaml style (quoted names, url list).
const esc = (s) => `"${s.replace(/"/g, '\\"')}"`;
const lines = [
	'# skills.yaml — sport-skill compilations (snowboard, hockey), merged into',
	'# the library alongside exercises.yaml. Same schema. Generated by',
	'# scripts/import-skills.mjs from the "* Skills Work.xlsx" sheets.',
	'exercises:'
];
for (const e of entries) {
	lines.push(`  - name: ${esc(e.name)}`);
	lines.push(`    id: ${e.id}`);
	lines.push(`    category: ${e.category}`);
	if (e.group) lines.push(`    group: ${esc(e.group)}`);
	if (e.url) lines.push(`    urls:\n      - ${esc(e.url)}`);
}
writeFileSync('skills.yaml', lines.join('\n') + '\n');
console.log(`wrote skills.yaml — ${entries.length} skills`);
const byCat = entries.reduce((m, e) => ((m[e.category] = (m[e.category] || 0) + 1), m), {});
console.log(byCat);
console.log('groups:', [...new Set(entries.map((e) => `${e.category}/${e.group}`))].join(', '));
