// Adv Log actuals importer.
//
// sources/Adv Log.xlsx is the current block's dated calendar
// (Day · Date · Plan · Actual · Life/Workout Notes). The Plan column is
// authored into programs/2026-race-prep.md; here we lift the COMPLETED days —
// rows with a non-empty Actual — into the log as D1 `sessions` against the
// current program. Set-level detail in the free-text Actual is left as notes;
// future sessions get logged structured via the app (M3).
//
// Emits:
//   log/adv-log.csv          date,day,plan,actual,notes  (inspection)
//   log/adv-log-seed.sql     D1 sessions (program_id = '2026-race-prep')
//
// Usage:  node scripts/import-adv-log.mjs

import XLSX from 'xlsx';
import { writeFileSync } from 'node:fs';

const SRC = 'sources/Adv Log.xlsx';
const PROGRAM = '2026-race-prep';

const clean = (v) => String(v ?? '').replace(/\s+/g, ' ').trim();
const csvCell = (v) => {
	const s = clean(v);
	return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const sqlStr = (v) => {
	const s = clean(v);
	return s ? `'${s.replace(/'/g, "''")}'` : 'NULL';
};
// "6/29/2026" → 2026-06-29
function isoDate(v) {
	const m = clean(v).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
	if (!m) return null;
	return `${m[3]}-${String(+m[1]).padStart(2, '0')}-${String(+m[2]).padStart(2, '0')}`;
}

const wb = XLSX.readFile(SRC);
const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1, blankrows: false, defval: '', raw: false });

const out = [['date', 'day', 'plan', 'actual', 'notes']];
const sql = [
	`-- Adv Log actuals seed (generated by scripts/import-adv-log.mjs).`,
	`-- Completed days of the current block; apply once D1 exists:`,
	`--   wrangler d1 execute switchback --file log/adv-log-seed.sql`,
	''
];
let seq = 0;
for (const r of rows.slice(1)) {
	const date = isoDate(r[1]);
	const plan = clean(r[2]);
	const actual = clean(r[3]);
	const life = clean(r[4]);
	if (!date || !actual) continue; // only completed days

	out.push([date, plan, plan, actual, life]);
	const notes = [actual, life].filter(Boolean).join(' — ');
	const id = `a${String(++seq).padStart(5, '0')}`;
	sql.push(
		`INSERT INTO sessions (id,date,program_id,day,completed_at,notes) VALUES ` +
			`('${id}','${date}',${sqlStr(PROGRAM)},${sqlStr(plan)},'${date}',${sqlStr(notes)});`
	);
}

writeFileSync('log/adv-log.csv', out.map((r) => r.map(csvCell).join(',')).join('\n') + '\n');
writeFileSync('log/adv-log-seed.sql', sql.join('\n') + '\n');
console.log(`adv-log: ${seq} completed sessions → log/adv-log.csv + log/adv-log-seed.sql`);
